// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package notifypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotifierServiceClient is the client API for NotifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifierServiceClient interface {
	ArticleCreationNotify(ctx context.Context, in *ArticleCreationRequest, opts ...grpc.CallOption) (*ArticleCreationResponse, error)
	UserCreationNotify(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserCreationResponse, error)
}

type notifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifierServiceClient(cc grpc.ClientConnInterface) NotifierServiceClient {
	return &notifierServiceClient{cc}
}

func (c *notifierServiceClient) ArticleCreationNotify(ctx context.Context, in *ArticleCreationRequest, opts ...grpc.CallOption) (*ArticleCreationResponse, error) {
	out := new(ArticleCreationResponse)
	err := c.cc.Invoke(ctx, "/notifypb.NotifierService/ArticleCreationNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifierServiceClient) UserCreationNotify(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserCreationResponse, error) {
	out := new(UserCreationResponse)
	err := c.cc.Invoke(ctx, "/notifypb.NotifierService/UserCreationNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifierServiceServer is the server API for NotifierService service.
// All implementations must embed UnimplementedNotifierServiceServer
// for forward compatibility
type NotifierServiceServer interface {
	ArticleCreationNotify(context.Context, *ArticleCreationRequest) (*ArticleCreationResponse, error)
	UserCreationNotify(context.Context, *UserCreationRequest) (*UserCreationResponse, error)
	mustEmbedUnimplementedNotifierServiceServer()
}

// UnimplementedNotifierServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotifierServiceServer struct {
}

func (UnimplementedNotifierServiceServer) ArticleCreationNotify(context.Context, *ArticleCreationRequest) (*ArticleCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleCreationNotify not implemented")
}
func (UnimplementedNotifierServiceServer) UserCreationNotify(context.Context, *UserCreationRequest) (*UserCreationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserCreationNotify not implemented")
}
func (UnimplementedNotifierServiceServer) mustEmbedUnimplementedNotifierServiceServer() {}

// UnsafeNotifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifierServiceServer will
// result in compilation errors.
type UnsafeNotifierServiceServer interface {
	mustEmbedUnimplementedNotifierServiceServer()
}

func RegisterNotifierServiceServer(s grpc.ServiceRegistrar, srv NotifierServiceServer) {
	s.RegisterService(&NotifierService_ServiceDesc, srv)
}

func _NotifierService_ArticleCreationNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServiceServer).ArticleCreationNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifypb.NotifierService/ArticleCreationNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServiceServer).ArticleCreationNotify(ctx, req.(*ArticleCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifierService_UserCreationNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifierServiceServer).UserCreationNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notifypb.NotifierService/UserCreationNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifierServiceServer).UserCreationNotify(ctx, req.(*UserCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifierService_ServiceDesc is the grpc.ServiceDesc for NotifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notifypb.NotifierService",
	HandlerType: (*NotifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArticleCreationNotify",
			Handler:    _NotifierService_ArticleCreationNotify_Handler,
		},
		{
			MethodName: "UserCreationNotify",
			Handler:    _NotifierService_UserCreationNotify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notifier/notifypb/notify.proto",
}
